const menu=document.querySelector('.menu-button');
const mobile=document.querySelector('#mobile-nav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));mobile.hidden=!open;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobile.hidden){mobile.hidden=true;menu.setAttribute('aria-expanded','false');menu.focus();}});
const tabs=[...document.querySelectorAll('[role="tab"]')];
function selectTab(tab){tabs.forEach(t=>{const selected=t===tab;t.setAttribute('aria-selected',String(selected));t.tabIndex=selected?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!selected;});}
tabs.forEach((tab,i)=>{tab.addEventListener('click',()=>selectTab(tab));tab.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();selectTab(tabs[next]);tabs[next].focus();});});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let count=0;document.querySelectorAll('[data-case]').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&button.dataset.filter!==card.dataset.case;if(!card.hidden)count++;});document.getElementById('no-projects').hidden=count!==0;}));
const form=document.getElementById('contact-form');
form?.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=new FormData(form);const text=[...data.entries()].map(([key,value])=>`${key}: ${String(value).trim()}`).join('\n\n');document.getElementById('enquiry-draft').value=text;document.getElementById('form-status').textContent=form.dataset.ready;document.getElementById('form-result').hidden=false;const subject=`Marine coating enquiry - ${String(data.get('company')).replace(/[\r\n]/g,' ')}`;window.location.href=`mailto:sgdw@DWMARINCOATS.COM?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(text)}`;});
document.getElementById('copy-enquiry')?.addEventListener('click',async()=>{const draft=document.getElementById('enquiry-draft');try{await navigator.clipboard.writeText(draft.value);document.getElementById('form-status').textContent=form.dataset.copied;}catch{draft.focus();draft.select();}});
